### PR TITLE
Python3

### LINKED ISSUE #2: Clean up debug messages
* remove unused
* replace `print()` with `debug()`, where `debug()` is going to be activated by command line option `--debug` later
* add debugging message in pynicotine2 in `readData()`

### LINKED ISSUE #3: Write commentary
* bytes <-> string problem  
** network communication
** opening files (pickle)
* Gtk/Gdk constants

### LINKED ISSUE #4: Rebase the f out of this mess of commits

### LINKED ISSUE #5: Get nicotine chat room running fully
Yeah, I know, blah blah title, but at this point I don't see a better way forward than repeatedly running the app and intervening at the point where it crashes

### LINKED ISSUE #9: Add --debug switch
And make `debug()`'s behavior depend on it

### LINKED ISSUE #11: Connect to other chat rooms
* right click on room and join
* join by double click

### LINKED ISSUE #13: Search files

### LINKED ISSUE #14: Download file(s)

### LINKED ISSUE #15: User info

### LINKED ISSUE #16: User browse

### PR DESCRIPTION
**Pull request by lene**

### CODE REVIEW

**Comment by eLvErDe** [comment]
Just saw your latest commit in your branch :D

Would you like to be added to nicotine org ? So you can commit directly in the project

**Comment by lene** [comment]
> Just saw your latest commit in your branch :D
> 
> Would you like to be added to nicotine org ? So you can commit directly in the project

Why not, thanks :) 

I'm not making any promises though, porting to Python 3 is a bigger pain than I anticipated. Maybe I'll abandon this project instead of getting on with it.

**Comment by eLvErDe** [comment]
Just did !


I agree and I was pretty impressed seeing the work done already. I tried 
myself and indeed the whole UI opens and look pretty good. I guess it 
never saves your account options, this is why it's not connecting, app 
think you have no account configured yet...


Adam.

**Comment by lene** [comment]
Thanks! 
I don't think that's the issue why it's not connecting, it's actually sending the username and password. Or claims it does, I suspect it dies silently in a separate thread because handling `bytes` has significantly changed in Python3. Anyway, I'll investigate further.

**Comment by droserasprout** [comment]
@lene, could you please take a quick look at my merge requests (ones starting with "Fix")? It seems like all major issues are resolved now – I use my branch containing mentioned fixes with real account and everything works fine.

**Comment by lene** [comment]
Hi @droserasprout, thank you, that is a lot of fixes! Sorry I did not reply earlier (and shame on GitHub notifications, I did not get any message you opened the PRs, what's up with that?) - I'll take a look at your PRs later today and get back to you and/or merge them directly!

**Review by kiplingw — APPROVED** [review]

**Review by kiplingw — APPROVED** [review]

**Pull request merged**
