### PR TITLE
Fix parsing Last Seen in Buddy List

### PR DESCRIPTION
**Pull request by droserasprout**
Fixes the following exception:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/droserasprout/nicotine-plus/src/pynicotine/nicotine.py", line 252, in run
    app = frame.MainApp(data_dir, config, plugins, trayicon, hidden, bindip, port)
  File "/home/droserasprout/nicotine-plus/src/pynicotine/gtkgui/frame.py", line 3776, in __init__
    self.frame = NicotineFrame(data_dir, config, plugins, trayicon, start_hidden, bindip, port)
  File "/home/droserasprout/nicotine-plus/src/pynicotine/gtkgui/frame.py", line 518, in __init__
    self.userlist = UserList(self)
  File "/home/droserasprout/nicotine-plus/src/pynicotine/gtkgui/userlist.py", line 203, in __init__
    iter = self.usersmodel.insert(0, row)
  File "/home/droserasprout/nicotine-plus/.venv/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1007, in insert
    return self._do_insert(position, row)
  File "/home/droserasprout/nicotine-plus/.venv/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 988, in _do_insert
    row, columns = self._convert_row(row)
  File "/home/droserasprout/nicotine-plus/.venv/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 900, in _convert_row
    result.append(self._convert_value(cur_col, value))
  File "/home/droserasprout/nicotine-plus/.venv/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 914, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/home/droserasprout/nicotine-plus/.venv/lib/python3.8/site-packages/gi/overrides/GObject.py", line 210, in __init__
    self.set_value(py_value)
  File "/home/droserasprout/nicotine-plus/.venv/lib/python3.8/site-packages/gi/overrides/GObject.py", line 266, in set_value
    _gi._gvalue_set(self, py_value)
OverflowError: 9223372036854775807 not in range -2147483648 to 2147483647
```

### CODE REVIEW

**Comment by lene** [comment]
Funny, I don't get that exception (am I right in assuming that you get it when you add a buddy who was never seen?). Anyway it fixes the bug for you, and the code looks way better than before, so I'm merging it.

**Comment by droserasprout** [comment]
@lene, for some reason three of my buddies do not exist. Initially I thought it's python3 port bug, but stable version shows the same. It seems like Soulseek server has wiped inactive accounts recently.

**Comment by lene** [comment]
I think the server continuously deactivates accounts that have not logged in for over a month. Once your buddys log back in they will be active again, unless somebody else has taken their usernames in the meantime.
More to the original point, I did test the buddy list with a user that didn't exist and it properly showed "Never seen", even before adding your patch. As our discussion on https://github.com/lene/nicotine-plus/issues/25 shows as well, apparently there are some differences in what bugs appear in Linux and in OSX.

**Comment by droserasprout** [comment]
Despite I test python3 port both on Linux and MacOS this exception has occurred while testing on Linux. I'll try to reproduce this once again and gather more data.

**Comment by lene** [comment]
I don't think you need to bother - the exception is fixed, both on Linux and MacOS, right? I don't see the need to figure out why *before* the fix the exception only occurred in some cases and not all.

**Pull request merged**
