### PR TITLE
Fix codestyle-related flake8 warnings

### PR DESCRIPTION
**Pull request by droserasprout**
Thanks for your effort put into this project, you're awesome! Sorry for a huge diff. So here's what going on here:

* Tab indentation replaced with 4-spaces one
* Imports converted to absolute to improve readability
* Semi-automatically fixed all codestyle related flake warnings like missing whitespaces, double whiespaces, "not X in" checks, bare excepts, "!= None" checks etc.
* Added poetry pyproject.toml and simple Makefile to make development a bit easier. Does not replace setup.py yet because of lack of package data support (shouldn't Make handle this?)
* Dockerfile slightly edited: added Wayland usage example, removed Ubuntu-specific python-* packages in favor of standard pip installation

No actual code logic has been changed, only linting this time.

### CODE REVIEW

**Comment by lene** [comment]
Hi, thanks so much for your work and sorry it took me so long to respond! I super appreciate your fixing ~3000 flake8 errors and warnings!

Sorry to say though, when trying to merge your PR I ran into massive merge conflicts. I seem to have solved all the conflicts, but I would ask you to please double check. I have created a new PR for that: #24 . I hope you don't mind me adding you as a collaborator on this repository (https://github.com/lene) and requesting a code review from you.

I could not find how you ran `flake8`, but when I run it on this codebase, I still get a bunch of errors. Could you either fix these as well, or update the `.flake8` config file to ignore them? I would like to get this branch clean enough to pass flake8 completely, so that I can use the flake8 run in the Github action (`.github/workflows/pythonapp.yml`) so that it fails any time a new flake8 violation is introduced. This would also solve issue #7 .

Regarding using poetry and the Makefile: I am not sure this is a decision we should make at this point, because it affects all developers working on nicotine+ and I don't think it is our call to make. Could you factor these changes out into a separate PR, please? (I checked if I could do that on my own by just reverting a commit or a few, but the changes don't appear to be strictly tied to one or some commits.)

**Comment by droserasprout** [comment]
Thanks for adding me to collaborators, I'm highly motivated to bring this app to live.

In this MR I've aimed the typos, 2to3 conversion artifacts and codestyle violations leaving the unobvious warnings untouched. The reason behind this (except for not changing things I don't understand enough yet) is to make clear the actual code problems left. I'll mark these with `noqa` in your rebased branch to make the pipelines green and come back to this later.

I've added Makefile and pyproject.toml to use tooling I'm familiar with during development, not to propose switching to it. Sorry for not cleaning this up and the messy commits overall.

**Comment by lene** [comment]
Thank you! To save some work for you, it might be better to add more exceptions to the `--ignore` options in flake8, instead of adding `#noqa` everywhere. Later, when cleaning up the less obvious problems, we can just remove the exceptions one by one.

**Comment by lene** [comment]
BTW I wasn't familiar with poetry, but it seems pretty neat. I'd like to keep it for the `Dockerfile` if not as a replacement for `setup.py`.

**Comment by droserasprout** [comment]
All unrelated changes at https://github.com/lene/nicotine-plus/pull/24 were reverted, now it's strictly about getting linter green:
``` bash
isort --force-single-line --recursive nicotine pynicotine plugins
# E402 module level import not at top of file
# E501 line too long
# W503 line break before binary operator
# W504 line break after binary operator
flake8 nicotine pynicotine plugins --ignore=E402,E501,W503,W504
```
Other lines with warnings have been marked with `noqa` (don't worry, I have a tiny script for that). I'll prepare a separate merge requests for tooling improvements later.

**Comment by lene** [comment]
Closing since #24 is merged now.

**Pull request closed without merging**
